name: build-windows-exe

on:
  push:
    tags:
      - 'v*'    # build when you push a tag like v1.0.0

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: desktop

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --name "Image Processing Toolkit" --onefile --windowed --noconfirm --add-data "assets;assets" --collect-all ttkbootstrap --icon "assets/app.ico" app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Image-Processing-Toolkit
          path: desktop/dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Image-Processing-Toolkit
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
